# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'ISSOKiosk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Square Point of Sale SDK (Trial)
  pod 'SquarePointOfSaleSDK', '~> 3.4'

  # Square Mobile Payments SDK (existing - keep for now)
  # This is already added via Swift Package Manager, but if you want to use CocoaPods instead:
  # pod 'SquareMobilePaymentsSDK', '~> 2.0'

end

